[package]
name = "first_rust_project"
version = "0.1.0"
authors = ["Arjun-Bakshi <arjunrbakshi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
